#!/usr/bin/env python3
"""Animate an existing brand post image into a short video.

Takes a still image already generated by create_post.py and adds motion via
fal.ai's Kling image-to-video model. No new image content is generated — the
exact on-model characters/scene from the still carry over, only motion is
added, which is why this only ever runs on an approved still rather than
generating a video from a text prompt alone.

By default this PREVIEWS: it downloads the video locally and does not queue
or publish it. Use --queue to add it to pending_posts.json, or --publish to
post it as a Reel immediately.

Usage:
    python animate_post.py --image generated/post-20260809-021204.png
    python animate_post.py --image generated/post-....png \
        --motion "the characters headbang to the beat, camera pushes in" \
        --publish
"""

from __future__ import annotations

import argparse
import datetime
import sys
from pathlib import Path

import httpx
from dotenv import load_dotenv

load_dotenv()

from content_engine import brand
from content_engine.image_gen import ImageGenError, host_image_publicly
from content_engine.llm_adapter import LLMError
from content_engine.poster import PostError
from content_engine.video_gen import VideoGenError, generate_video_from_image

from daily_post import _enqueue_pending_post, _post_with_retries, _remove_pending_post

_GENERATED_DIR = Path(__file__).parent / "generated"

_DEFAULT_MOTION = (
    "Bring this exact scene to life with subtle, natural motion. Keep every "
    "character, color, and background element exactly as shown — do not add "
    "new characters, objects, or text. Camera slowly pushes in."
)


def main() -> None:
    parser = argparse.ArgumentParser(description="Animate a still post image into a short video.")
    parser.add_argument("--brand", default=None, help="Brand key under brands/ (default: $BRAND or jammy-o).")
    parser.add_argument(
        "--image", required=True, type=Path, help="Path to a still image from create_post.py."
    )
    parser.add_argument(
        "--motion",
        default=_DEFAULT_MOTION,
        help="Describes the desired animation. Keep it about motion, not new content.",
    )
    parser.add_argument("--duration", default="5", help="Video length in seconds, 3-15 (default: 5).")
    parser.add_argument(
        "--no-audio",
        action="store_true",
        help="Disable native audio generation (silent Reel). Audio is on by default.",
    )
    parser.add_argument(
        "--topic",
        default=None,
        help="Caption topic (used only with --queue/--publish).",
    )
    parser.add_argument(
        "--caption",
        choices=["witty", "none"],
        default="witty",
        help="'witty' (default): one short witty sentence. 'none': no caption at all.",
    )
    parser.add_argument(
        "--queue", action="store_true", help="Add the video to pending_posts.json after previewing."
    )
    parser.add_argument(
        "--publish", action="store_true", help="Publish to Instagram as a Reel immediately."
    )
    args = parser.parse_args()

    if not args.image.exists():
        sys.exit(f"Image not found: {args.image}")
    if args.publish:
        args.queue = True

    now = datetime.datetime.now()
    style = brand.load_style(brand=args.brand)

    print(f"[{now}] Uploading source image for public hosting...")
    try:
        image_url = host_image_publicly(args.image)
    except ImageGenError as e:
        print(f"[{now}] Hosting failed: {e}", file=sys.stderr)
        sys.exit(1)
    print(f"[{now}] Source image URL: {image_url}")

    with_audio = not args.no_audio
    print(f"[{now}] Motion prompt:\n{args.motion}\n")
    print(f"[{now}] Generating video (duration={args.duration}s, audio={with_audio})...")
    try:
        video_url = generate_video_from_image(
            image_url,
            args.motion,
            duration=args.duration,
            generate_audio=with_audio,
        )
    except VideoGenError as e:
        print(f"[{now}] Video generation failed: {e}", file=sys.stderr)
        sys.exit(1)
    print(f"[{now}] Video ready: {video_url}")

    _GENERATED_DIR.mkdir(exist_ok=True)
    video_path = _GENERATED_DIR / f"video-{now.strftime('%Y%m%d-%H%M%S')}.mp4"
    with httpx.Client(timeout=120) as client:
        r = client.get(video_url)
        r.raise_for_status()
        video_path.write_bytes(r.content)
    print(f"[{now}] Video saved locally: {video_path}")

    if not args.queue:
        print(f"\n[{now}] Preview complete — nothing was queued or published.")
        print(f"  Local file: {video_path}")
        print(f"  CDN URL:    {video_url}")
        print(f"  To queue:   rerun with --queue (or --publish to post immediately)")
        return

    topic = args.topic or "Jammy-O and Pineapple video"
    if args.caption == "none":
        caption = ""
        print(f"[{now}] Caption: (none)")
    else:
        print(f"[{now}] Generating caption...")
        try:
            caption = brand.generate_short_caption(style, topic)
        except LLMError as e:
            print(f"[{now}] Caption generation failed: {e}", file=sys.stderr)
            sys.exit(1)
        print(f"[{now}] Caption ready: {caption}\n")

    pending = _enqueue_pending_post(
        media_type="video",
        topic=topic,
        caption=caption,
        media_url=video_url,
    )
    print(f"[{now}] Queued pending post: {pending['id']}")

    if not args.publish:
        print(f"\n[{now}] Queued — nothing was published.")
        print(f"  Publish: python daily_post.py --retry-pending")
        return

    print(f"[{now}] Publishing Reel to Instagram...")
    try:
        post_id = _post_with_retries(pending, max_attempts=3)
    except PostError as e:
        print(f"[{now}] Post failed: {e}", file=sys.stderr)
        print(f"[{now}] Kept in queue. Retry with: python daily_post.py --retry-pending", file=sys.stderr)
        sys.exit(1)
    _remove_pending_post(pending["id"])
    print(f"[{now}] Done! Post ID: {post_id}")


if __name__ == "__main__":
    main()
